/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.barcode;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Font;
import com.itextpdf.text.Image;
import com.itextpdf.text.List;
import com.itextpdf.text.ListItem;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Rectangle;
import com.itextpdf.text.pdf.BaseFont;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.PrintJob;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import org.krysalis.barcode4j.impl.code128.Code128Bean;
import org.krysalis.barcode4j.output.bitmap.BitmapCanvasProvider;
import org.krysalis.barcode4j.tools.UnitConv;

/**
 *
 * @author Shamil
 */
public class CreateBarcode extends javax.swing.JFrame {

String Mehsuladi = "Kisi Salvari";
String olcusu = "XXL";
String rengi = "Qara";
String qiymeti = "20.00 man";
    

    public CreateBarcode() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        id = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("generate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtArea.setColumns(20);
        txtArea.setRows(5);
        txtArea.setText("         Venera Geyim ve");
        jScrollPane1.setViewportView(txtArea);

        jButton2.setText("Print button");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(385, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(65, 65, 65)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(111, 111, 111))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {
            CreatePdfAndBarcode();

        } catch (Exception ex) {

        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        

try{
           txtArea.print();

}catch(Exception ex){

}

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateBarcode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateBarcode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateBarcode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateBarcode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateBarcode().setVisible(true);
            }
        });
    }

    public void CreatePdfAndBarcode() throws DocumentException, IOException {
        
              
        

        Code128Bean code128 = new Code128Bean();
        final int dpi = 150;
        code128.setHeight(12f);
        code128.setModuleWidth(UnitConv.in2mm(3.0f / dpi));
        code128.setQuietZone(10);
        code128.doQuietZone(true);

        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        BitmapCanvasProvider canvas = new BitmapCanvasProvider(baos, "image/x-png", 400, BufferedImage.TYPE_BYTE_BINARY, false, 0);
        code128.generateBarcode(canvas, id.getText());
        canvas.finish();

//write to png file
        FileOutputStream fos = new FileOutputStream("C:\\burayaz\\barcode.png");
        fos.write(baos.toByteArray());
        fos.flush();
        fos.close();

//write to pdf
        Image png = Image.getInstance(baos.toByteArray());
        png.setAbsolutePosition(0, 705);
        png.scalePercent(25);

        BaseFont baseFont = BaseFont.createFont(/*"resources/ARIAL.TTF"*/"c:/Windows/Fonts/arial.ttf", BaseFont.IDENTITY_H, true);
        Font pageNumberFont = new Font(Font.FontFamily.UNDEFINED, (float) 0.5, Font.BOLDITALIC);
        Font pageNumberFont2 = new Font(Font.FontFamily.UNDEFINED, (float) 0.5, Font.BOLDITALIC);
        Font pageNumberFont3 = new Font(Font.FontFamily.HELVETICA, (float) 1.0, Font.BOLD);

        Document document;
        document = new Document(new Rectangle((float) 21.5, (float) 14.9));
        document.setMargins(1, 1, (float) 0.0001, (float) 0.001);
        PdfPTable table = new PdfPTable(1);
        table.getDefaultCell().setBorder(PdfPCell.NO_BORDER);
        table.setWidthPercentage(100);
        
        //table.addCell(png);

        // for (int aw = 0; aw < 27; aw++) {
        Paragraph p = new Paragraph("                Venera", pageNumberFont);
        Paragraph pp = new Paragraph("     Geyim ve Tekstil Dünyasi", pageNumberFont2);

//            table.setSpacingBefore(1f);
//            table.setSpacingAfter(1f);
//            
// //            p.add(createImageCell(png));
//            PdfPTable intable = new PdfPTable(1);
//            intable.setSpacingBefore(1f);
//            intable.setSpacingAfter(3f);
//            intable.getDefaultCell().setBorder(PdfPCell.NO_BORDER);
//            //intable.addCell(p);
//            //intable.addCell(pp);
        table.addCell(png);
        table.getDefaultCell().setBorder(0);

        List orderlist = new List(List.ALIGN_CENTER);
        orderlist.add(new ListItem("Malin adi :" + Mehsuladi, pageNumberFont3));
        orderlist.add(new ListItem("Ölçüsü :" + olcusu, pageNumberFont3));
        orderlist.add(new ListItem("Rengi :" + rengi, pageNumberFont3));
        orderlist.add(new ListItem("Qiymeti :" + qiymeti, pageNumberFont3));

        // table.addCell(p);
        //table.addCell(pp);
        //table.addCell(intable);
        //  }
//        table.setBorder(Border.NO_BORDER);
        Paragraph p2 = new Paragraph("Product Name");
        p2.add("\nPrice:500");
        p2.add(png);
        PdfWriter writer = PdfWriter.getInstance(document, new FileOutputStream("C:\\burayaz\\barcodes.pdf"));
        document.open();
//        document.add();

        //document.add(table);
        document.add(p);
        document.add(pp);
        document.add(orderlist);
        table.setSpacingBefore(0.0f);
        table.setSpacingAfter(0.001f);
        document.add(table);
        document.close();

        writer.close();




    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtArea;
    // End of variables declaration//GEN-END:variables

}
